// <auto-generated />
namespace PasswordManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movies));
        
        string IMigrationMetadata.Id
        {
            get { return "201412131723141_Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
